"""Formal Xiezhi Decision v0.1 threshold algorithm.

Pipeline: Observation -> Candidate Evaluation -> Risk Assessment ->
Decision Selection -> AlgorithmDecision v1 output.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite
from uuid import uuid4

from vision2grasp.intelligence.blueprint import (
    AlgorithmBlueprint,
    AlgorithmMetadata,
    AlgorithmStatus,
    AlgorithmType,
    BlueprintStage,
)
from vision2grasp.intelligence.contracts import (
    INTELLIGENCE_DECISION_SCHEMA_VERSION,
    AlgorithmDecision,
    AlgorithmObservation,
    CandidateEvidence,
    DecisionAction,
    DecisionStatus,
)


XIEZHI_DECISION_V0_1_ID = "xiezhi_decision_v0_1"
XIEZHI_DECISION_V0_1_VERSION = "v0.1"
_STAGE_IDS = (
    "observation",
    "candidate_evaluation",
    "risk_assessment",
    "decision_selection",
    "decision_output",
)


@dataclass(frozen=True, slots=True)
class XiezhiDecisionV01Config:
    max_position_std_m: float = 0.020
    max_rotation_std_rad: float = 0.12
    min_candidate_score: float = 0.75

    def __post_init__(self) -> None:
        for name in ("max_position_std_m", "max_rotation_std_rad"):
            value = getattr(self, name)
            if not isfinite(value) or value < 0:
                raise ValueError(f"{name} must be finite and non-negative")
        if not isfinite(self.min_candidate_score) or not 0 <= self.min_candidate_score <= 1:
            raise ValueError("min_candidate_score must be in [0, 1]")


@dataclass(frozen=True, slots=True)
class CandidateEvaluation:
    candidate_id: str
    planner_score: float
    evidence_confidence: float | None
    decision_score: float
    executable: bool

    def public_metadata(self) -> dict[str, object]:
        return {
            "candidate_id": self.candidate_id,
            "planner_score": self.planner_score,
            "evidence_confidence": self.evidence_confidence,
            "decision_score": self.decision_score,
            "executable": self.executable,
        }


@dataclass(frozen=True, slots=True)
class RiskAssessment:
    candidate_id: str | None
    risk_estimation: float | None
    position_std_proxy_m: float | None
    rotation_std_proxy_rad: float | None
    acceptable: bool
    reasons: tuple[str, ...]

    def public_metadata(self) -> dict[str, object]:
        return {
            "candidate_id": self.candidate_id,
            "risk_estimation": self.risk_estimation,
            "position_std_proxy_m": self.position_std_proxy_m,
            "rotation_std_proxy_rad": self.rotation_std_proxy_rad,
            "acceptable": self.acceptable,
            "reasons": list(self.reasons),
        }


@dataclass(frozen=True, slots=True)
class DecisionSelection:
    action: DecisionAction
    selected_candidate_id: str | None
    reason: str

    def public_metadata(self) -> dict[str, str | None]:
        return {
            "action": self.action.value,
            "selected_candidate_id": self.selected_candidate_id,
            "reason": self.reason,
        }


XIEZHI_DECISION_V0_1_BLUEPRINT = AlgorithmBlueprint(
    blueprint_id="xiezhi.decision.v0_1",
    provider_id="xiezhi",
    algorithm_id=XIEZHI_DECISION_V0_1_ID,
    algorithm_version=XIEZHI_DECISION_V0_1_VERSION,
    stages=(
        BlueprintStage(
            "observation",
            "Observation",
            "AlgorithmObservation",
            "AlgorithmObservation",
            "Consume Gongshu state representation and candidate pool.",
            "decision_v0_1.py",
            "observe()",
        ),
        BlueprintStage(
            "candidate_evaluation",
            "Candidate Evaluation",
            "AlgorithmObservation",
            "CandidateEvaluation[]",
            "Score only candidates generated by Gongshu.",
            "decision_v0_1.py",
            "evaluate_candidates()",
        ),
        BlueprintStage(
            "risk_assessment",
            "Risk Assessment",
            "CandidateEvaluation[]",
            "RiskAssessment",
            "Estimate transparent heuristic risk and uncertainty bounds.",
            "decision_v0_1.py",
            "assess_risk()",
        ),
        BlueprintStage(
            "decision_selection",
            "Decision Selection",
            "RiskAssessment",
            "DecisionSelection",
            "Choose execution or reobservation without controlling the robot.",
            "decision_v0_1.py",
            "select_decision()",
        ),
        BlueprintStage(
            "decision_output",
            "Decision Output",
            "DecisionSelection",
            "AlgorithmDecision v1",
            "Emit the stable Gongshu Intelligence decision contract.",
            "decision_v0_1.py",
            "output_decision()",
        ),
    ),
    edges=tuple(zip(_STAGE_IDS, _STAGE_IDS[1:])),
    parameters={
        "max_position_std_m": 0.020,
        "max_rotation_std_rad": 0.12,
        "min_candidate_score": 0.75,
    },
)

XIEZHI_DECISION_V0_1_METADATA = AlgorithmMetadata(
    algorithm_id=XIEZHI_DECISION_V0_1_ID,
    name="Xiezhi Decision",
    version=XIEZHI_DECISION_V0_1_VERSION,
    type=AlgorithmType.XIEZHI_ALGORITHM,
    description="Transparent deterministic decision authority over Gongshu-generated grasp candidates.",
    status=AlgorithmStatus.EXPERIMENTAL,
    source="Gongshu Intelligence Layer / Xiezhi",
    created_time="2026-09-16T18:25:46+08:00",
    blueprint_reference=XIEZHI_DECISION_V0_1_BLUEPRINT.blueprint_id,
    provider_id="xiezhi",
    decision_contract=INTELLIGENCE_DECISION_SCHEMA_VERSION,
    stages=_STAGE_IDS,
    capabilities=("candidate_evaluation", "risk_assessment", "decision_selection", "decision_explanation"),
)


class XiezhiDecisionV01:
    """Deterministic, inspectable v0.1 decision authority."""

    metadata = XIEZHI_DECISION_V0_1_METADATA
    blueprint = XIEZHI_DECISION_V0_1_BLUEPRINT

    def __init__(self, config: XiezhiDecisionV01Config = XiezhiDecisionV01Config()) -> None:
        self.config = config

    @staticmethod
    def observe(observation: AlgorithmObservation) -> AlgorithmObservation:
        if not isinstance(observation, AlgorithmObservation):
            raise TypeError("Xiezhi Decision v0.1 requires AlgorithmObservation")
        return observation

    @staticmethod
    def _decision_score(candidate: CandidateEvidence, confidence: float | None) -> float:
        if confidence is None:
            return float(candidate.score)
        return float((candidate.score + confidence) / 2.0)

    def evaluate_candidates(
        self, observation: AlgorithmObservation
    ) -> tuple[CandidateEvaluation, ...]:
        evaluations = (
            CandidateEvaluation(
                candidate_id=candidate.candidate_id,
                planner_score=float(candidate.score),
                evidence_confidence=observation.evidence_confidence,
                decision_score=self._decision_score(candidate, observation.evidence_confidence),
                executable=candidate.executable,
            )
            for candidate in observation.candidates
            if candidate.executable
        )
        return tuple(sorted(evaluations, key=lambda item: item.decision_score, reverse=True))

    def assess_risk(
        self,
        observation: AlgorithmObservation,
        evaluations: tuple[CandidateEvaluation, ...],
    ) -> RiskAssessment:
        confidence = observation.evidence_confidence
        position_std = None if confidence is None else 0.004 + (1.0 - confidence) * 0.032
        rotation_std = None if confidence is None else 0.03 + (1.0 - confidence) * 0.18
        selected = evaluations[0] if evaluations else None
        reasons: list[str] = []
        if selected is None:
            reasons.append("NO_EXECUTABLE_CANDIDATE")
        if position_std is None:
            reasons.append("POSITION_UNCERTAINTY_UNKNOWN")
        elif position_std > self.config.max_position_std_m:
            reasons.append("POSITION_UNCERTAINTY_HIGH")
        if rotation_std is None:
            reasons.append("ROTATION_UNCERTAINTY_UNKNOWN")
        elif rotation_std > self.config.max_rotation_std_rad:
            reasons.append("ROTATION_UNCERTAINTY_HIGH")
        if selected is not None and selected.decision_score < self.config.min_candidate_score:
            reasons.append("CANDIDATE_SCORE_LOW")
        return RiskAssessment(
            candidate_id=None if selected is None else selected.candidate_id,
            risk_estimation=None if selected is None else float(1.0 - selected.decision_score),
            position_std_proxy_m=position_std,
            rotation_std_proxy_rad=rotation_std,
            acceptable=not reasons,
            reasons=tuple(reasons),
        )

    @staticmethod
    def select_decision(risk: RiskAssessment) -> DecisionSelection:
        if risk.acceptable and risk.candidate_id is not None:
            return DecisionSelection(
                DecisionAction.EXECUTE_GRASP,
                risk.candidate_id,
                "uncertainty_and_quality_acceptable",
            )
        return DecisionSelection(
            DecisionAction.REOBSERVE,
            None,
            "uncertainty_unknown_or_high_or_candidate_poor",
        )

    def output_decision(
        self,
        observation: AlgorithmObservation,
        evaluations: tuple[CandidateEvaluation, ...],
        risk: RiskAssessment,
        selection: DecisionSelection,
    ) -> AlgorithmDecision:
        strongest = evaluations[0] if evaluations else None
        uncertainty = tuple(dict.fromkeys((*observation.uncertainty_reasons, *risk.reasons)))
        return AlgorithmDecision(
            decision_id=f"decision-{uuid4().hex[:16]}",
            observation_id=observation.observation_id,
            provider_id=self.metadata.provider_id,
            algorithm_id=self.metadata.algorithm_id,
            status=DecisionStatus.ACTION_AVAILABLE,
            selected_action=selection.action,
            selected_candidate_id=selection.selected_candidate_id,
            confidence=(
                observation.evidence_confidence
                if strongest is None
                else strongest.decision_score
            ),
            risk_estimation=risk.risk_estimation,
            reason=selection.reason,
            uncertainty=uncertainty,
            diagnostics={
                "algorithm": self.metadata.public_metadata(),
                "blueprint_id": self.blueprint.blueprint_id,
                "pipeline_stages": list(self.metadata.stages),
                "candidate_evaluations": [item.public_metadata() for item in evaluations],
                "risk_assessment": risk.public_metadata(),
                "decision_selection": selection.public_metadata(),
                "provider_score_type": "MEAN_PLANNER_RANKING_AND_EVIDENCE_CONFIDENCE",
            },
        )

    def decide(self, observation: AlgorithmObservation) -> AlgorithmDecision:
        observed = self.observe(observation)
        evaluations = self.evaluate_candidates(observed)
        risk = self.assess_risk(observed, evaluations)
        selection = self.select_decision(risk)
        return self.output_decision(observed, evaluations, risk, selection)


__all__ = [
    "CandidateEvaluation",
    "DecisionSelection",
    "RiskAssessment",
    "XIEZHI_DECISION_V0_1_BLUEPRINT",
    "XIEZHI_DECISION_V0_1_ID",
    "XIEZHI_DECISION_V0_1_METADATA",
    "XIEZHI_DECISION_V0_1_VERSION",
    "XiezhiDecisionV01",
    "XiezhiDecisionV01Config",
]
