"""Gongshu Intelligence Layer public surface."""

from .contracts import (
    AlgorithmDecision,
    AlgorithmObservation,
    CandidateEvidence,
    DecisionAction,
    DecisionStatus,
)
from .service import IntelligenceService
from .registry import AlgorithmRegistry, default_algorithm_registry
from .blueprint import (
    AlgorithmBlueprint,
    AlgorithmMetadata,
    AlgorithmStatus,
    AlgorithmType,
    BlueprintStage,
)
from .external_baseline import (
    EXTERNAL_BASELINE_PROVIDER_ID,
    MOCK_EXTERNAL_BASELINE_ID,
    MOCK_EXTERNAL_BASELINE_METADATA,
    ExternalAlgorithm,
    ExternalBaselineAdapter,
    ExternalBaselineInput,
    ExternalBaselineOutput,
    ExternalCandidateInput,
    MockExternalBaseline,
    MockSelectionStrategy,
    create_mock_external_baseline_provider,
)
from .arena import (
    AlgorithmArenaBackend,
    AlgorithmRun,
    ArenaAlgorithmReference,
    ArenaExperiment,
    ArenaExperimentStatus,
    ArenaResultStore,
    ResultRecord,
)
from .arena_runner import (
    AlgorithmArenaRunner,
    ArenaExecution,
    ArenaRunStore,
    ArenaValidation,
    ArenaValidationOutcome,
    MockArenaValidation,
)
from .visualization import (
    ActiveAlgorithmView,
    DecisionEngineView,
    DecisionEvidenceView,
    DecisionHistoryEntry,
    DecisionRuntimeView,
    VisualizationDataProvider,
    XiezhiDashboardState,
)
from .switcher import (
    ACTIVE_ALGORITHM_SCHEMA_VERSION,
    ActiveAlgorithm,
    ActiveAlgorithmSelector,
    AlgorithmLoader,
    DecisionEngine,
)

__all__ = [
    "AlgorithmDecision",
    "AlgorithmBlueprint",
    "AlgorithmMetadata",
    "AlgorithmStatus",
    "AlgorithmType",
    "AlgorithmRegistry",
    "AlgorithmLoader",
    "AlgorithmObservation",
    "CandidateEvidence",
    "BlueprintStage",
    "DecisionAction",
    "DecisionEngine",
    "DecisionStatus",
    "IntelligenceService",
    "ACTIVE_ALGORITHM_SCHEMA_VERSION",
    "ActiveAlgorithm",
    "ActiveAlgorithmSelector",
    "EXTERNAL_BASELINE_PROVIDER_ID",
    "MOCK_EXTERNAL_BASELINE_ID",
    "MOCK_EXTERNAL_BASELINE_METADATA",
    "ExternalAlgorithm",
    "ExternalBaselineAdapter",
    "ExternalBaselineInput",
    "ExternalBaselineOutput",
    "ExternalCandidateInput",
    "MockExternalBaseline",
    "MockSelectionStrategy",
    "create_mock_external_baseline_provider",
    "AlgorithmArenaBackend",
    "AlgorithmRun",
    "ArenaAlgorithmReference",
    "ArenaExperiment",
    "ArenaExperimentStatus",
    "ArenaResultStore",
    "ResultRecord",
    "AlgorithmArenaRunner",
    "ArenaExecution",
    "ArenaRunStore",
    "ArenaValidation",
    "ArenaValidationOutcome",
    "MockArenaValidation",
    "DecisionEngineView",
    "ActiveAlgorithmView",
    "DecisionEvidenceView",
    "DecisionHistoryEntry",
    "DecisionRuntimeView",
    "VisualizationDataProvider",
    "XiezhiDashboardState",
    "default_algorithm_registry",
]
