from __future__ import annotations

from pathlib import Path
import unittest

from test_intelligence_runtime import make_outcome
from vision2grasp.intelligence import IntelligenceService


PROJECT_ROOT = Path(__file__).resolve().parents[1]
GONGSHU_ROOT = PROJECT_ROOT / "frontend" / "apps" / "gongshu"


class AlgorithmBlueprintVisualizationTests(unittest.TestCase):
    def setUp(self) -> None:
        service = IntelligenceService(xiezhi_enabled=True)
        service.decide(make_outcome())
        dashboard = service.dashboard_state()
        assert dashboard is not None
        self.dashboard = dashboard.public_metadata()
        self.blueprint = self.dashboard["engine"]["blueprint"]
        assert self.blueprint is not None

    def test_xiezhi_decision_v0_1_blueprint_loads_from_dashboard(self) -> None:
        self.assertEqual(
            self.dashboard["schema_version"],
            "gongshu.xiezhi-dashboard/v1",
        )
        self.assertEqual(self.dashboard["runtime"]["current_algorithm"], "Xiezhi Decision")
        self.assertEqual(self.dashboard["engine"]["algorithm_version"], "v0.1")
        self.assertEqual(
            self.blueprint["schema_version"],
            "gongshu.algorithm-blueprint/v1",
        )

    def test_blueprint_node_list_follows_registered_stage_and_edge_data(self) -> None:
        self.assertEqual(
            [stage["name"] for stage in self.blueprint["stages"]],
            [
                "Observation",
                "Candidate Evaluation",
                "Risk Assessment",
                "Decision Selection",
                "Decision Output",
            ],
        )
        self.assertEqual(len(self.blueprint["edges"]), 4)

    def test_blueprint_node_detail_includes_code_and_contract_information(self) -> None:
        node = next(
            stage
            for stage in self.blueprint["stages"]
            if stage["stage_id"] == "candidate_evaluation"
        )
        self.assertEqual(node["module"], "decision_v0_1.py")
        self.assertEqual(node["function"], "evaluate_candidates()")
        self.assertEqual(node["input_contract"], "AlgorithmObservation")
        self.assertEqual(node["output_contract"], "CandidateEvaluation[]")
        self.assertEqual(
            node["description"],
            "Score only candidates generated by Gongshu.",
        )

    def test_blueprint_visualization_is_driven_by_dashboard_data(self) -> None:
        html = (GONGSHU_ROOT / "index.html").read_text(encoding="utf-8")
        script = (GONGSHU_ROOT / "xiezhi-blueprint.js").read_text(encoding="utf-8")
        self.assertIn('data-xiezhi-entry="blueprint"', html)
        self.assertIn('id="xiezhiBlueprintDialog"', html)
        self.assertIn('src="./xiezhi-blueprint.js"', html)
        for source in (
            "blueprint?.stages",
            "blueprint?.edges",
            "stage.module",
            "stage.function",
            "stage.input_contract",
            "stage.output_contract",
        ):
            self.assertIn(source, script)
        for hardcoded_stage in (
            "Candidate Evaluation",
            "Risk Assessment",
            "Decision Selection",
            "Decision Output",
        ):
            self.assertNotIn(hardcoded_stage, script)
        self.assertIn("dialog.showModal()", script)


if __name__ == "__main__":
    unittest.main()
